### PR TITLE
[TBD] OAuth: URL encoded credentials are not parsed correctly by the backend

### PR DESCRIPTION
**Pull request by mxr576**
If a value contains any special character (like % in a password) then it gets encoded which leads to a malformed payload.

Needs test coverage.

### CODE REVIEW

**Comment by mxr576** [comment]
Something is off here, the original code supposes to be correct, but if it is correct then special characters should not be allowed in values (and keys) because `application/x-www-form-urlencoded` [means](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST) that "Non-alphanumeric characters in both keys and values are percent encoded:". Consequently, for example, if a value has `%` then it has to be encoded to `%25` , but that malformed the original input and authentication fails.

I checked what the `get_token` [script](https://docs.apigee.com/api-platform/system-administration/auth-tools) does and it also uses curl's `--data-urlencode` parameter (instead of just `--data`) for username and password, which has the same unexpected side-effect.

Although, there is this other documentation about [Get the machine user's OAuth2 tokens](https://docs.apigee.com/api-platform/system-administration/automating-tasks#get-the-machine-users-oauth2-tokens) and there is a "cheat" in that because it does not use either `--data` or `--data-urlencode`, it just builds the raw request body (without encoding the values).

@cnovak can you share your thoughts about it, or check with engineering what is the expected behavior here?

**Comment by cnovak** [comment]
Thanks @mxr576 for bringing this to our attention, will have the team look into it.

**Comment by mxr576** [comment]
Updated the title, it reflects the issue more clearly based on my current knowledge.
Yesterday I ran an additional test with Postman and the same issue happened. When I set the `application/x-www-form-urlencoded` header, Postman automatically started to percent encode the key-value pairs in the request body which lead to the same issue.

**Comment by mxr576** [comment]
`sudo re-open`

**Pull request closed without merging**
