### PR TITLE
Add union type to suppress deprecation warning

### LINKED ISSUE #323: Fetching class constant class of deprecated class Http\Message\UriFactory since version 1.1...
## Description
`Fetching class constant class of deprecated class Http\Message\UriFactory since version 1.1, use Psr\Http\Message\UriFactoryInterface instead.` 

The above deprecation error is thrown on  `\Apigee\Edge\ClientInterface::getUriFactory()` on a project that has PHPStan and PHPStan Deprecation Rules configured.

## Steps to Reproduce
-

## Actual Behavior
- 

## Expected Behavior
Make the code deprecation free without BC break in a non-major version.

## Screenshots
-

## Notes
-
## Version Info
3.0.2

### PR DESCRIPTION
**Pull request by mxr576**
Closes #323

### CODE REVIEW

**Comment by mxr576** [comment]
:thinking: ...
```
$ vendor/vimeo/psalm/psalm --config=psalm.xml.dist --show-info=false --stats
Warning: "findUnusedBaselineEntry" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedBaselineEntry" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Warning: "findUnusedCode" will default to "true" in Psalm 6. You should explicitly enable or disable this setting.
Target PHP version: 8.1 (inferred from composer.json) (unsupported extensions: reflection).
Scanning files...
Analyzing files...



------------------------------
                              
       No errors found!       
                              
------------------------------
937 other issues found.
You can display them with --show-info=true
------------------------------

Checks took 0.13 seconds and used 15.467MB of memory
No files analyzed
Psalm was able to infer types for 93.0589% of the codebase
-----------------

```

**Comment by mxr576** [comment]
I do not know why I could not reproduce the issue locally but I managed to fix it... :100: :D

**Review by divya-intelli — APPROVED** [review]
LGTM

**Comment by divya-intelli** [comment]
> vendor/vimeo/psalm/psalm --config=psalm.xml.dist --show-info=false --stats

Thank you @mxr576 for the fix, I was locally able to replicate the psalm error and the fix looks good.

**Pull request merged**
