### PR TITLE
Bump minimum required version of symfony/serializer

### LINKED ISSUE #373: Unable to install 3.0.6 on Drupal 10.3.2 or on any version that requires symfony/serializer:>6.4.6
## Description
There was an issue with Symfony Serializer 6.4.7 but that was a long time ago and since https://github.com/apigee/apigee-client-php/commit/3073f76dff563f7de88487697a6b218b7d6adc1f was merged Symfony released several patch versions for 6.4.x branch and 6.4.9 has the issue fixed: https://github.com/symfony/symfony/pull/57580

Because `drupal/core-recommended` locks on specific version of dependencies, the Apigee Edge Drupal module cannot be installed on Drupal 10.3.2 (or on any other version) that requires a never version of Symfony Serializer.

Next time before a release, it should checked if there is a never version from the dependency that was locked to a specific version range or a conflict rule was added and whether that version addresses the reason behind the version lock or not.

## Steps to Reproduce

`composer create-project drupal/recommended-project:~10.3.0`

```sh
$ composer req drupal/apigee_edge:~3.0.8
./composer.json has been updated

  Problem 1
    - Root composer.json requires drupal/apigee_edge ~3.0.8 -> satisfiable by drupal/apigee_edge[3.0.8].
    - apigee/apigee-client-php 3.0.6 conflicts with symfony/serializer >6.4.6.
    - drupal/core-recommended 10.3.2 requires symfony/serializer ~v6.4.7 -> satisfiable by symfony/serializer[v6.4.10].
    - drupal/apigee_edge 3.0.8 requires apigee/apigee-client-php ~3.0.6 -> satisfiable by apigee/apigee-client-php[3.0.6].
    - drupal/core-recommended is locked to version 10.3.2 and an update of this package was not requested.

```

## Actual Behavior
What happened after the steps to reproduce.

## Version Info
In what version or versions of this library can you
reproduce this issue?

### PR DESCRIPTION
**Pull request by mxr576**
Closes #373

### CODE REVIEW

**Comment by mxr576** [comment]
Interesting... tests are still broken with 6.4.10, what are we doing wrong in our code? Or there is still in an issue with Symfony Serializer?

**Comment by mxr576** [comment]
Somebody should take a look at whether any of these open issues relates to what we experience here...

https://github.com/symfony/symfony/issues?q=is%3Aissue+is%3Aopen+label%3ASerializer

**Comment by kedarkhaire** [comment]
Hi @mxr576 
We will check it. 
Thanks!

**Comment by shishir-intelli** [comment]
@mxr576 
Thank you for creating this PR, 
The fix for test case failing on this PR is resolved here https://github.com/apigee/apigee-client-php/pull/376
We will merge this and PR 376 together.

**Comment by mxr576** [comment]
Thx, I am glad the issue is close be to solved. I only had a couple of seconds to take a look on that PR and left a feedback. Closing this one.

**Pull request closed without merging**
