### PR TITLE
Fix handling of empty response

### LINKED ISSUE #363: Fatal error: Uncaught TypeError: Apigee\Edge\Api\Management\Controller\AppByOwnerController::responseArrayToArrayOfEntities(): Argument #1 ($responseArray) must be of type array,
## Description
When a developer has no apps yet on Apigee X the following type error is triggered:

```
Fatal error: Uncaught TypeError: Apigee\Edge\Api\Management\Controller\AppByOwnerController::responseArrayToArrayOfEntities(): Argument #1 ($responseArray) must be of type array, bool given, called in /mnt/files/local_mount/build/vendor/apigee/apigee-client-php/src/Controller/NonPaginatedEntityListingControllerTrait.php on line 52 and defined in /mnt/files/local_mount/build/vendor/apigee/apigee-client-php/src/Controller/EntityListingControllerTrait.php:42
Stack trace:

```

## Steps to Reproduce

```
<?php

require_once $_composer_autoload_path ?? __DIR__ . '/../vendor/autoload.php';

use Apigee\Edge\Client;

$env = json_decode(getenv('APIGEE_SERVICE_ACCOUNT_KEY'), TRUE);

$client = new Client(new \Apigee\Edge\HttpClient\Plugin\Authentication\ApigeeOnGcpOauth2(
    $env['client_email'],
    $env['private_key'],
new \Apigee\Edge\Tests\Test\HttpClient\Plugin\InMemoryOauthTokenStorage(),
), \Apigee\Edge\ClientInterface::APIGEE_ON_GCP_ENDPOINT);


$email = 'developer' . bin2hex(random_bytes(5)) . '@example.com';
//$foo = (new \Apigee\Edge\Api\Management\Controller\OrganizationController($client))->load($env['project_id']);
(new \Apigee\Edge\Api\Management\Controller\DeveloperController(
    $env['project_id'],
    $client,
))->create(new \Apigee\Edge\Api\Management\Entity\Developer([
    'firstName' => 'John',
    'lastName' => 'Doe',
    'email' => $email,
    'userName' => $email,
]));
(new \Apigee\Edge\Api\Management\Controller\DeveloperAppController(
    $env['project_id'],
    $email,
    $client,
))->getEntities();

```

## Version Info
3.0.5

### PR DESCRIPTION
**Pull request by mxr576**
Closes https://github.com/apigee/apigee-client-php/issues/363

### CODE REVIEW

**Comment by mxr576** [comment]
Test failures looks unrelated... what is happening?

**Comment by kedarkhaire** [comment]
Hi @mxr576 
The codecov-actions fails due to the invalid key, we will update the key soon also the PR will be updated soon #360.
The other 7 failures on tests might be due to the upgraded vendors, we are looking into it on this PR #362 with issue #361 
Thanks!

**Comment by mxr576** [comment]
@kedarkhaire Hi, do you have an update on when the failing test suites in master will be fixed?

**Review by kedarkhaire — APPROVED** [review]
LGTM

**Pull request merged**
