### PR TITLE
Changes for symfony 6.2 upgrade

### LINKED ISSUE #254: Update apigee-client-php to use Symfony 6.2
Upgrade to Symfony 5.4 as an intermediate step to symfony 6 upgrade.

### PR DESCRIPTION
**Pull request by divya-intelli**
Fix for errors when symfony is upgraded to 6.2. 
Fixes #254

### CODE REVIEW

**Review by shishir-intelli — APPROVED** [review]
LGTM

**Comment by mxr576** [comment]
Can somebody also reference all those issues from https://github.com/apigee/apigee-client-php/issues?q=is%3Aissue+is%3Aopen+label%3A%22Drupal+10+Preparation%22 that this PR resolves?

I am asking because we were planning to contribute to D10 prep tasks, but we do not see clearly what is in WIP state already and where help is needed.

**Comment by divya-intelli** [comment]
@mxr576 , 

Thank you so much for offering help. We really appreciate it.

This PR resolves the issue that we were facing while upgrading to symfony 6.2. 
After merging this PR we will update the Drupal modules to support Drupal 10. 
We have also marked the tickets which we need help with tag "help wanted".

**Comment by mxr576** [comment]
Opened a follow up issue regarding the merged changes: #269

>  We have also marked the tickets which we need help with tag "help wanted".

Thanks, that is not too many :) 

Can some of these closed also?
https://github.com/apigee/apigee-client-php/issues?q=is%3Aissue+is%3Aopen+label%3A%22Drupal+10+Preparation%22

**Pull request merged**
