### PR TITLE
Closes-#108 - After creating app without description throwing php not…

### LINKED ISSUE #108: Notice in recent message logs if description is empty after creating app in Apigee hybrid
## Description
Notice in recent message logs if description is empty after creating app in Apigee hybrid

## Steps to Reproduce
Create an app with empty description

`Notice: Undefined property: stdClass::$value in Apigee\Edge\Denormalizer\AttributesPropertyDenormalizer->denormalize() (line 57 of \vendor\apigee\apigee-client-php\src\Denormalizer\AttributesPropertyDenormalizer.php)`

### PR DESCRIPTION
**Pull request by shishir-intelli**
Should fix #108 , Checking $value and handled if it is undefined in $data.

### CODE REVIEW

**Comment by mxr576** [comment]
This is a duplicate of #122

**Comment by mxr576** [comment]
@shishir-intelli please add test coverage to #122 if you have time, that is required to merge the fix.

**Comment by raakesh-blokhra** [comment]
> @shishir-intelli please add test coverage to #122 if you have time, that is required to merge the fix.

@mxr576 I'll look into the test coverage. I will have to look into #122 as well and make the required changes. Are you suggesting that we shouldn't merge this fix till test coverages are up to date?

**Comment by cnovak** [comment]
> we shouldn't merge this fix till test coverages are up to date?

We should be adding tests for any changes we make that are not already covered by tests.

**Review by phdhiren — APPROVED** [review]
LGTM. Let's merge it for now and add test case as separate PR.

**Pull request merged**
