### PR TITLE
[M10N-144] Fix PHP notices produced when the developer is not set.

### LINKED ISSUE #144: Notices on Rate Plan Detail Page
**Describe the bug**
Certain rate plan detail pages have notices.

**To Reproduce**
1. Log in with the tsnow-mint org.
2. Go to `/user/1/monetization/package/multiple_products-c4xp/plan/multiple_products-c4xp_rev_share_and_rate_card`
3. See 4 notices 

**Expected behavior**
No notices should appear.

**Screenshots**
m10n-rate-plan-notices
m10n-rate-plan-notices-bartik

**Additional context**

`Notice: Undefined property: stdClass::$developer in Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization() (line 64 of /Users/jacine/Sites/kickstart_m10n/vendor/apigee/apigee-client-php/src/Api/Monetization/Denormalizer/DeveloperRatePlanDenormalizer.php).`

```
Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL) (Line: 73)
Apigee\Edge\Api\Monetization\Denormalizer\RatePlanDenormalizerFactory->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 261)
Symfony\Component\Serializer\Serializer->getDenormalizer(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 181)
Symfony\Component\Serializer\Serializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 76)
Apigee\Edge\Serializer\EntitySerializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface') (Line: 48)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->responseArrayToArrayOfEntities(Array) (Line: 83)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->getEntities(, ) (Line: 101)
Drupal\apigee_m10n\Entity\Storage\Controller\RatePlanSdkControllerProxy->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 103)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->Drupal\apigee_m10n\Entity\Storage\{closure}(Object) (Line: 217)
Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController(Object) (Line: 111)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 156)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadFutureRatePlan(Object) (Line: 369)
Drupal\apigee_m10n\Entity\RatePlan->getFutureRatePlan() (Line: 328)
Drupal\apigee_m10n\Entity\RatePlan->getFuturePlanLinks()
call_user_func(Array) (Line: 297)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->getFieldValue('futurePlanLinks') (Line: 273)
Drupal\apigee_m10n\Entity\RatePlan->getFieldValue('futurePlanLinks') (Line: 250)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->get('futurePlanLinks') (Line: 329)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'full') (Line: 285)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 242)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

`Notice: Trying to get property 'isCompany' of non-object in Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization() (line 64 of /Users/jacine/Sites/kickstart_m10n/vendor/apigee/apigee-client-php/src/Api/Monetization/Denormalizer/DeveloperRatePlanDenormalizer.php).`

```
Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL) (Line: 73)
Apigee\Edge\Api\Monetization\Denormalizer\RatePlanDenormalizerFactory->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 261)
Symfony\Component\Serializer\Serializer->getDenormalizer(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 181)
Symfony\Component\Serializer\Serializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 76)
Apigee\Edge\Serializer\EntitySerializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface') (Line: 48)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->responseArrayToArrayOfEntities(Array) (Line: 83)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->getEntities(, ) (Line: 101)
Drupal\apigee_m10n\Entity\Storage\Controller\RatePlanSdkControllerProxy->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 103)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->Drupal\apigee_m10n\Entity\Storage\{closure}(Object) (Line: 217)
Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController(Object) (Line: 111)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 156)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadFutureRatePlan(Object) (Line: 369)
Drupal\apigee_m10n\Entity\RatePlan->getFutureRatePlan() (Line: 328)
Drupal\apigee_m10n\Entity\RatePlan->getFuturePlanLinks()
call_user_func(Array) (Line: 297)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->getFieldValue('futurePlanLinks') (Line: 273)
Drupal\apigee_m10n\Entity\RatePlan->getFieldValue('futurePlanLinks') (Line: 250)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->get('futurePlanLinks') (Line: 329)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'full') (Line: 285)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 242)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

`Notice: Undefined property: stdClass::$developer in Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization() (line 64 of /Users/jacine/Sites/kickstart_m10n/vendor/apigee/apigee-client-php/src/Api/Monetization/Denormalizer/DeveloperRatePlanDenormalizer.php).`

```
Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL) (Line: 61)
Apigee\Edge\Api\Monetization\Denormalizer\RatePlanDenormalizerFactory->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 182)
Symfony\Component\Serializer\Serializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 76)
Apigee\Edge\Serializer\EntitySerializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface') (Line: 48)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->responseArrayToArrayOfEntities(Array) (Line: 83)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->getEntities(, ) (Line: 101)
Drupal\apigee_m10n\Entity\Storage\Controller\RatePlanSdkControllerProxy->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 103)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->Drupal\apigee_m10n\Entity\Storage\{closure}(Object) (Line: 217)
Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController(Object) (Line: 111)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 156)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadFutureRatePlan(Object) (Line: 369)
Drupal\apigee_m10n\Entity\RatePlan->getFutureRatePlan() (Line: 328)
Drupal\apigee_m10n\Entity\RatePlan->getFuturePlanLinks()
call_user_func(Array) (Line: 297)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->getFieldValue('futurePlanLinks') (Line: 273)
Drupal\apigee_m10n\Entity\RatePlan->getFieldValue('futurePlanLinks') (Line: 250)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->get('futurePlanLinks') (Line: 329)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'full') (Line: 285)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 242)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

`Notice: Trying to get property 'isCompany' of non-object in Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization() (line 64 of /Users/jacine/Sites/kickstart_m10n/vendor/apigee/apigee-client-php/src/Api/Monetization/Denormalizer/DeveloperRatePlanDenormalizer.php).
Apigee\Edge\Api\Monetization\Denormalizer\DeveloperRatePlanDenormalizer->supportsDenormalization(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL) (Line: 61)`

```
Apigee\Edge\Api\Monetization\Denormalizer\RatePlanDenormalizerFactory->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 182)
Symfony\Component\Serializer\Serializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface', NULL, Array) (Line: 76)
Apigee\Edge\Serializer\EntitySerializer->denormalize(Object, 'Apigee\Edge\Api\Monetization\Entity\RatePlanInterface') (Line: 48)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->responseArrayToArrayOfEntities(Array) (Line: 83)
Apigee\Edge\Api\Monetization\Controller\RatePlanController->getEntities(, ) (Line: 101)
Drupal\apigee_m10n\Entity\Storage\Controller\RatePlanSdkControllerProxy->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 103)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->Drupal\apigee_m10n\Entity\Storage\{closure}(Object) (Line: 217)
Drupal\apigee_edge\Entity\Storage\EdgeEntityStorageBase->withController(Object) (Line: 111)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadPackageRatePlans('multiple_products-c4xp', 1) (Line: 156)
Drupal\apigee_m10n\Entity\Storage\RatePlanStorage->loadFutureRatePlan(Object) (Line: 369)
Drupal\apigee_m10n\Entity\RatePlan->getFutureRatePlan() (Line: 328)
Drupal\apigee_m10n\Entity\RatePlan->getFuturePlanLinks()
call_user_func(Array) (Line: 297)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->getFieldValue('futurePlanLinks') (Line: 273)
Drupal\apigee_m10n\Entity\RatePlan->getFieldValue('futurePlanLinks') (Line: 250)
Drupal\apigee_edge\Entity\FieldableEdgeEntityBase->get('futurePlanLinks') (Line: 329)
Drupal\Core\Entity\EntityViewBuilder->buildComponents(Array, Array, Array, 'full') (Line: 285)
Drupal\Core\Entity\EntityViewBuilder->buildMultiple(Array) (Line: 242)
Drupal\Core\Entity\EntityViewBuilder->build(Array)
call_user_func(Array, Array) (Line: 378)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 582)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 156)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 693)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Version Info**

- rc1 in Kickstart.
- rc1 with Bartik

### PR DESCRIPTION
**Pull request by Jaesin**
Fixes https://github.com/apigee/apigee-m10n-drupal/issues/144

### CODE REVIEW

**Comment by mxr576** [comment]
I'll check this next week because IIRC the fixed logic is also used elsewhere and that property should be available always on existing developer specific rate plans based on testing that I did when I developed this code. Maybe the rate plans is malformed? Do you have other developer rate plan that you can reproduce this bug?

**Comment by mxr576** [comment]
Yes, I remember now, I created the problematic rate plan and try to push the limits of the API (again ;P) so I really would like to see a step by step guide how this problem could be reproduced in normal circumstances and understand the _real problem behind_ without just blindly fixing the problem you see in m10n.

**Comment by Jaesin** [comment]
Since developer is a nullable property in the `DeveloperPropertyAwareTrait` trait and could be not set, it doesn't make since to assume it's there.

**Comment by mxr576** [comment]
Syntactically you are right, but semantically you are not. As I can see I forgot to explain in a comment on the trait as I did in other places that: The property can be only `null` when you construct an entity object that contains this trait _in PHP_ but ** it cannot be null after the entity has been created on the API**. Even the API response for the POST requests contains the `developer` object set and the PHP API client automatically sets the `developer` property's value on the sent object so subsequent calls can access to the object.

It is a unique design of the Apigee APIs that they expect some required properties as part of the URL parameters (ex.: developer/api product/package ids, etc) and some as part of the request payload. 

So even if your reasoning would be correct, you should rather check `RatePlanInterface::TYPE_DEVELOPER == $data->type && isset($data->developer)` instead of what is in your PR at this moment.

BUT, as I explained this issue should not occur because the `RatePlanInterface::TYPE_DEVELOPER == $data->type` ensures that this denormalizer only gets called on developer rate plans and if rate plan is a developer rate plan then it must contain the nested developer object in `$data->developer` and on that object the `company` property must be either `false` or `true`. (Unless you are serializing an "incomplete" developer rate plan constructed in the PHP side that you should not.)

This is the reason why I am asking whether you can show me another rate plan that this problem occurs - preferable not from this test org that I used to hack the MINT API while I developed the integration - or you can provide a step by step guide how to create a malformed developer rate plan object like the one that I (accidentally) created as `multiple_products-c4xp_rev_share_and_rate_card`.

**Comment by cnovak** [comment]
This fixed an issue found in an org, but may be an edge case so not something we need to get in right away, but is a better check that what was previously there.

**Comment by mxr576** [comment]
> This fixed an issue found in an org, but may be an edge case so not something we need to get in right away, but is a better check that what was previously there.

This is exactly the opposite that I tried to suggest in my previous comment. We should not merge a bug fix until
1. we are not sure what is the actual bug, IOW we are convinced that it is an actual bug in this library
2. we are unable to reproduce it and cover it with a test case

I do not think that we were able to fulfill either 1 or 2 this time, we just merged something that "fixes" something that we experienced in a playground environment.

The changed logic is also used elsewhere in this library, so now 1% of this library behaves differently than the other 99% where this logic is being used. :roll_eyes: 

With this approach, sooner or later this library becomes an unmaintainable monolith...

**Pull request merged**
